### PR TITLE
#25 Preserving original data on encrypted partition.

### PR DESCRIPTION
**Pull request by MMG-DG**
My rough idea to preserve any original data in encrypted partition before it is encrypted and formatted.

### CODE REVIEW

**Comment by sergioprado** [comment]
@MMG-DG thanks for contributing!

I have some comments on your PR, but you will need to rebase it after https://github.com/toradex/meta-toradex-security/pull/24 is merged.

So let's wait for https://github.com/toradex/meta-toradex-security/pull/24 to be merged, then you will be able to rebase this one and we can start the review process.

**Comment by sergioprado** [comment]
@MMG-DG https://github.com/toradex/meta-toradex-security/pull/24 was merged.

Would you please rebase your changes and resend the PR?

**Comment by MMG-DG** [comment]
@sergioprado - I believe I have now rebased with all the latest changes.

Happy to take any comments as this was just my initial changes to get something working.

**Comment by sergioprado** [comment]
It seems there are merge commit sin your PR. There should be only one commit with your change I guess. Would you please review it?

**Pull request closed without merging**
