### PR TITLE
u-boot: add missing patch for upstream modules (kirkstone only)

### PR DESCRIPTION
**Pull request by rborn-tx**
Commit 9459b6fe70cac8570b0fd879c422c49692674c3e (u-boot: add patches to show message when CLI access is allowed) missed the patch for upstream modules which is being fixed here.

Detected by CI.

### CODE REVIEW

**Comment by sergioprado** [comment]
@rborn-tx Is this ready for review/merge?

**Comment by rborn-tx** [comment]
> @rborn-tx Is this ready for review/merge?

Almost :slightly_smiling_face:. I'm performing a local build to confirm and once it's done I'll assign the reviewers :muscle:.

**Comment by rborn-tx** [comment]
Should be ready for review now.

**Review by sergioprado — APPROVED** [review]
LGTM

**Review by jsrc27 — APPROVED** [review]
LGTM as well.

**Comment by rborn-tx** [comment]
Merging then.

**Pull request merged**
