### PR TITLE
Torizon rename

### PR DESCRIPTION
**Pull request by EdTheBearded**
Change the old TorizonCore name on our layer to the new Torizon OS.

Closes https://github.com/torizon/meta-toradex-torizon/issues/81

### CODE REVIEW

**Comment by sergioprado** [comment]
Would you please just remove "Closes #81" from the commit message, as this doesn't mean anything here in this layer?

**Comment by EdTheBearded** [comment]
> Would you please just remove "Closes #81" from the commit message, as this doesn't mean anything here in this layer?

Done.

**Comment by leograba** [comment]
Btw, I'm too late to this discussion, but for the future I'd like to let you know that using a full reference such as  `Closes torizon/meta-toradex-torizon#81` is possible.

That's the GitHub way to reference an issue on another organization and repo: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests

**Comment by sergioprado** [comment]
> Btw, I'm too late to this discussion, but for the future I'd like to let you know that using a full reference such as Closes torizon/meta-toradex-torizon#81 is possible.

@leograba yes, if we can reference issues from other projects on GitHub (I guess that is the case now for meta-toradex-torizon), then it is certainly acceptable.

**Pull request merged**
