### PR TITLE
layer.conf: make it compatible with scarthgap

### PR DESCRIPTION
**Pull request by EdTheBearded**
fixes torizon/meta-toradex-torizon#51

### CODE REVIEW

**Comment by sergioprado** [comment]
Currently, there is no development happening on the `main` branch. Is the `main` branch being used for something?

**Comment by EdTheBearded** [comment]
Hi @sergioprado. Currently it is only being "used" by Jenkins on our weekly build of the master. And due to recent changes from Yocto, that build started failing due to layer compatibility.

**Review by jsrc27 — APPROVED** [review]
From my side it looks fine just to unblock our internal builds. I'll wait for everyone else to chime in though if they want.

**Comment by rborn-tx** [comment]
> From my side it looks fine just to unblock our internal builds. I'll wait for everyone else to chime in though if they want.

Same from me.

**Review by rborn-tx — APPROVED** [review]

**Pull request merged**
